workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: codemagik api key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: org.antasonlus.agendantas
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Deep clean all caches
        script: |
          flutter clean
          rm -rf ~/.pub-cache
          rm -rf build/
          rm -rf .dart_tool/
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf Runner.xcworkspace/xcuserdata
          cd ..
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate
          pod setup
          pod install --repo-update

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=1.1.3 \
            --build-number=24 \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
